/**
 * `agenttrust_demo_state` — return the three pre-warmed devnet
 * counterparties from the pay-sh-demo's `devnet-counterparties.json`,
 * plus the demo's network + program metadata.
 *
 * The file lives at `examples/pay-sh-demo/devnet-counterparties.json`
 * and is regenerated by `scripts/prewarm-counterparties.ts`. The MCP
 * server reads it at request time so the tool always reflects the
 * latest pre-warm.
 */

import * as fs from "fs";
import * as path from "path";

import { z } from "zod";

import { explorerUrl } from "../../config";
import type { Tool, ToolContext } from "../types";

const InputSchema = z.object({});
type Input = z.infer<typeof InputSchema>;

interface Counterparty {
  id:                 number;
  label:              string;
  demoTier:           number;
  asset:              string;
  agentAccount:       string;
  atomStats:          string;
  owner:              string;
  registerSig:        string;
  initializeStatsSig: string;
  registeredAtSlot:   number;
  initializedAtSlot:  number;
  explorerUrls: {
    asset:        string;
    agentAccount: string;
    atomStats:    string;
  };
}

interface Output {
  available:      boolean;
  network?:       string;
  programs?:      Record<string, string>;
  baseCollection?: string;
  rootConfig?:    string;
  atomConfig?:    string;
  registryConfig?: string;
  counterparties?: Counterparty[];
  updatedAt?:     string;
  error?:         string;
  /** Resolved path the file was read from (for diagnostics). */
  source?:        string;
}

function findDemoFile(): string | null {
  const candidates = [
    // Env override wins (tests + power-users)
    process.env.PAY_SH_DEMO_STATE_FILE ?? "",
    // npm-install path: snapshot bundled into dist/embedded-data/ at
    // build time by scripts/copy-embedded-assets.js (Phase N1 fix).
    path.resolve(__dirname, "../../embedded-data/devnet-counterparties.json"),
    // Local-clone path: read directly from the source-of-truth file.
    path.resolve(__dirname, "../../../../examples/pay-sh-demo/devnet-counterparties.json"),
    // Process cwd fallback (tests, custom layouts).
    path.resolve(process.cwd(), "examples/pay-sh-demo/devnet-counterparties.json"),
  ].filter(Boolean);
  for (const p of candidates) {
    try {
      if (p && fs.existsSync(p)) return p;
    } catch { /* ignore */ }
  }
  return null;
}

export const demoStateTool: Tool<Input, Output> = {
  name:        "agenttrust_demo_state",
  description:
    "Return the three pre-warmed devnet demo counterparties (tier-0 untrusted, " +
    "tier-1 low-trust, tier-3 trusted). Each entry includes the asset pubkey, " +
    "Quantu agent_account / atom_stats PDAs, and Explorer URLs. Useful as input " +
    "for agenttrust_simulate_payment.",
  inputSchema: InputSchema,

  async handler(_input: Input, ctx: ToolContext): Promise<Output> {
    const file = findDemoFile();
    if (!file) {
      return {
        available: false,
        error:
          "Demo counterparty snapshot not found. The published MCP package " +
          "bundles it; if you've cleared PAY_SH_DEMO_STATE_FILE or are " +
          "running from a custom build without the bundled snapshot, set " +
          "PAY_SH_DEMO_STATE_FILE to a counterparties JSON path to override.",
      };
    }
    try {
      const raw    = fs.readFileSync(file, "utf-8");
      const parsed = JSON.parse(raw);
      const counterparties: Counterparty[] = (parsed.counterparties ?? []).map(
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (c: any) => ({
          id:                 Number(c.id),
          label:              String(c.label),
          demoTier:           Number(c.demoTier),
          asset:              String(c.asset),
          agentAccount:       String(c.agentAccount),
          atomStats:          String(c.atomStats),
          owner:              String(c.owner),
          registerSig:        String(c.registerSig),
          initializeStatsSig: String(c.initializeStatsSig),
          registeredAtSlot:   Number(c.registeredAtSlot),
          initializedAtSlot:  Number(c.initializedAtSlot),
          explorerUrls: {
            asset:        explorerUrl(ctx.chain.cfg, "address", String(c.asset)),
            agentAccount: explorerUrl(ctx.chain.cfg, "address", String(c.agentAccount)),
            atomStats:    explorerUrl(ctx.chain.cfg, "address", String(c.atomStats)),
          },
        }),
      );
      return {
        available:      true,
        network:        parsed.network,
        programs:       parsed.programs,
        baseCollection: parsed.baseCollection,
        rootConfig:     parsed.rootConfig,
        atomConfig:     parsed.atomConfig,
        registryConfig: parsed.registryConfig,
        counterparties,
        updatedAt:      parsed.updatedAt,
        source:         file,
      };
    } catch (err) {
      return { available: false, error: `failed to read demo state: ${(err as Error).message}`, source: file };
    }
  },
};
